# Generated by Django 4.0 on 2021-12-08 17:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_home_page_content_friendly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_content',
            name='hero_caroussel',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
