# Generated by Django 4.0 on 2021-12-08 19:56

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_content_home_page_content_carousell_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_content',
            name='middle_content',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
