# Generated by Django 4.0 on 2021-12-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_home_page_content_middle_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_page_content',
            name='middle_content',
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='middle_text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
