# Generated by Django 4.0 on 2021-12-08 20:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_home_page_content_middle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_content',
            name='middle_picture',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
