# Generated by Django 4.0 on 2021-12-08 20:27

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_home_page_content_fam_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_content',
            name='testimonials',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
