# Generated by Django 4.0 on 2021-12-08 20:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_home_page_content_testimonials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_page_content',
            old_name='testimonials',
            new_name='first_testimonial',
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='second_testimonial',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='third_testimonial',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
