# Generated by Django 3.2.7 on 2021-12-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_testimonials_home_page_content_first_testimonial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_page_content',
            name='carousell_photos',
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='carousell_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='home/carousell/'),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='carousell_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='home/carousell/'),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='carousell_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='home/carousell/'),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='first_testimonial_pic',
            field=models.ImageField(blank=True, null=True, upload_to='home/testimonials/'),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='second_testimonial_pic',
            field=models.ImageField(blank=True, null=True, upload_to='home/testimonials/'),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='third_testimonial_pic',
            field=models.ImageField(blank=True, null=True, upload_to='home/testimonials/'),
        ),
        migrations.AlterField(
            model_name='home_page_content',
            name='fam_picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/portfolio/'),
        ),
        migrations.AlterField(
            model_name='home_page_content',
            name='middle_picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/middle_picture/'),
        ),
        migrations.AlterField(
            model_name='home_page_content',
            name='prew_picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/portfolio/'),
        ),
        migrations.AlterField(
            model_name='home_page_content',
            name='w_picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/portfolio/'),
        ),
    ]
