# Generated by Django 3.2.7 on 2022-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211220_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram_mosaic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_pk', models.CharField(max_length=1000, null=True)),
                ('insta_id', models.CharField(max_length=1000, null=True)),
                ('code', models.CharField(max_length=1000, null=True)),
                ('taken_at', models.DateField(null=True)),
                ('media_type', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(max_length=1000, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('caption_text', models.CharField(max_length=1000, null=True)),
                ('video_url', models.CharField(max_length=1000, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('video_duration', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
