# Generated by Django 3.2.7 on 2022-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_instagram_mosaic'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram_mosaic',
            name='user',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
