# Generated by Django 3.2.7 on 2022-04-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_instagram_mosaic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram_mosaic',
            old_name='thumbnail_url',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='instagram_mosaic',
            name='user',
        ),
    ]
