# Generated by Django 3.2.7 on 2022-05-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220421_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_content',
            name='middle_text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
