# Generated by Django 3.2.7 on 2022-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_home_page_content_middle_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_page_content',
            name='first_testimonial',
        ),
        migrations.RemoveField(
            model_name='home_page_content',
            name='second_testimonial',
        ),
        migrations.RemoveField(
            model_name='home_page_content',
            name='third_testimonial',
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='first_testimonial_partner_1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='first_testimonial_partner_2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='first_testimonial_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='second_testimonial_partner_1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='second_testimonial_partner_2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='second_testimonial_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='third_testimonial_partner_1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='third_testimonial_partner_2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page_content',
            name='third_testimonial_text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
