# Generated by Django 3.2.7 on 2022-06-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='bio/cover/')),
                ('first_text', models.TextField(max_length=1000, null=True)),
                ('second_photo', models.ImageField(blank=True, null=True, upload_to='bio/second/')),
                ('second_text', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
