# Generated by Django 3.2.7 on 2021-12-16 20:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=150, null=True)),
                ('pre_desc', models.CharField(max_length=500, null=True)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=500, null=True)),
                ('cover', jsonfield.fields.JSONField(null=True)),
                ('description', models.TextField(null=True)),
                ('photos', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
