# Generated by Django 3.2.7 on 2022-02-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_album_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumPhotos',
            new_name='AlbumPhoto',
        ),
    ]
