# Generated by Django 3.2.7 on 2022-02-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220215_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/covers/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='photos',
            field=models.ImageField(upload_to='portfolio/albums/'),
        ),
    ]
