# Generated by Django 3.2.7 on 2022-02-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20220215_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
    ]
