# Generated by Django 3.2.7 on 2022-02-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_album_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='type',
            new_name='category',
        ),
    ]
