# Generated by Django 3.2.7 on 2022-02-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_album_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='portfolio.album'),
        ),
    ]
