# Generated by Django 3.2.7 on 2022-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_albumphoto_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
