# Generated by Django 3.2.7 on 2022-05-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_albumphoto_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumphoto',
            name='position',
        ),
    ]
